# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
  - 'vendor/**/*'
  - 'db/**/*'
  - 'bin/**/*'
  - 'spec/**/*'
  - 'node_modules/**/*'
  - 'lib/tasks/auto_annotate_models.rake'
  DisplayCopNames: true

Layout/MultilineBlockLayout:
  Exclude:
  - 'spec/**/*_spec.rb'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 30
  Exclude:
  - 'Gemfile'
  - 'config/**/*'
  - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  CountComments: false
  Max: 30

Naming/AccessorMethodName:
  Exclude:
  - 'app/controllers/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
  - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false